### ISSUE TITLE
fallback function not showing

### ISSUE THREAD

**Issue by Alexis-Falquier** [spacemanholdings/qmix#1]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/qtum-project/Lobby)
```

**Current behavior**

when deploying the contract fallback function is not displayed alongside all the other functions.

**Expected behavior**

fallback function should be displayed 

**Minimal reproduction of the problem with instructions**

deploy this contract on qmix.qtum.org:

```
pragma solidity ^ 0.4.18;

contract testingContract {
    
    function testingContract() public {
        
    }
      
    function () public payable {
        
    }
    
    function getBalance() constant public returns(uint){
        return this.balance;
    }
   
}
```

only getBalance will be displayed not fallback function

**What is the motivation / use case for changing the behavior?**

cannot send funds to contract on reg test environment and suspect this issue is related

* **Qmix Version:

unknown (4/4/2018 using qmix.qtum.org)

**Comment by smartcontracts** [comment]
Confirming this issue. Offending code is here:

https://github.com/spacemanholdings/qmix-revamp/blob/816ea7120af50d629fa3b1d5cc5d4d559f4761c1/src/client/app/shared/components/sidebar/run-tab/run-tab.component.ts#L53-L57

Testing a fix atm.
