### ISSUE TITLE
Solidity versions not pulling correctly

### ISSUE THREAD

**Issue by Alexis-Falquier** [spacemanholdings/qmix#22]
- Solidity versions not showing up in the option box.

- 'latest current release' is set to 0.4.19

- latest compiler version that actually compiles is 0.4.18

**Comment by spacemandev-git** [comment]
I'm unable to replicate. The dropdown shows all the releases for me. Latest local release means the latest one that's installed on your computer (which is also 0.4.19 for me) but if you click the drop down all the others show up.

**Comment by spacemandev-git** [comment]
Specific adblocker was preventing dropdrop to show up
